name: Deploy to Vercel

on:
  push:
    branches:
      - main
  # 可以手动触发部署
  workflow_dispatch:

jobs:
  deploy_to_vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            src/
            vercel.json
            package.json
            .gitignore
      
      - name: Trigger Vercel Deployment via Webhook
        run: |
          # 使用提供的Vercel部署挂钩URL直接触发部署
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_bPhyw2Ie6aZ7HKV4syrm06266CwK/B44WNZLvmT"
          echo "触发Vercel部署成功"
      
      - name: Verify deployment files exist
        run: |
          echo "检查必要的部署文件是否存在..."
          ls -la src/
          ls -la config/
          # 检查vercel.json配置文件
          if [ -f "vercel.json" ]; then
            echo "Vercel配置文件存在:" 
            cat vercel.json
            echo "Package.json文件存在:" 
            cat package.json
          else
            echo "错误: 未找到vercel.json配置文件"
          fi